### ISSUE TITLE
Issue about Anime Scene Dataset

### ISSUE THREAD

**Issue by tanfy929** [Yuxinn-J/Scenimefy#13]
Hello,
I am trying to replicate your project, but I encountered an issue with downloading the movie data ''The Place Promised in Our Early Days''.  It seems that I have no  access rights on Google Drive. Could you please check the sharing settings or provide an alternative link to access the file?
Thank you for your assistance!

**Comment by Yuxinn-J** [comment]
Hi there,
Thank you for your interest in the project! Unfortunately, we don’t have the rights to distribute the movie data directly. We can only provide links to publicly available content, like the files on Google Drive. Since we aren’t the hosts of these files, I’m unable to modify the sharing settings. :( Thanks for your understanding.

**Comment by Yuxinn-J** [comment]
I’ve sent over the extracted frames from the movie "The Place Promised in Our Early Days" to help out. For accessing the full movie, I recommend checking legal sources or public domain repositories.
Best, Yuxin

**Comment by tanfy929** [comment]
Thank you for your reply! The issue has been successfully solved
